params:
  name: "YourOnly.One" # your company name
  primaryauthor: "ᜌᜓᜃᜒ (Yuki ・ 雪亮)" # Used as primary author if no specific is set
  copyright: ""
  logourl: "" # Used in structured data as logo url
  keywords: [""] # Can be overriden per page
  imageurl: "" # Used in structured data as background image
  contact: "" # Primary email address
  phone: "" # Primary phone
  color: "#000000"
  pricerange: "$$" # Used in structured data as price range
  primarylocation: "enschede" # Used as primary location if no specific is set
  social:
    website: "https://YourOnly.One"
    github: "techmagus"
    facebook: "YourOnly.One0"
    facebook_admin: "183794425326191"  # This needs to be a page admin to get domain insights
    twitter: "YourOnlyOne7"
    twitter_domain: "YourOnly.One" # This domain shows in twitter cards as "View on `twitter_domain`"
    pinterest: ""
    instagram: "YourOnly.One"
    youtube: ""
    linkedin: ""

#module:
#  hugoVersion:
#    #extended: true
#    min: 0.88.0
#    #max: ''
