# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Semantic Web for Hugo"
license = "MIT"
licenselink = "https://github.com/YourOnly-One/hugo-semantic-web/blob/master/LICENSE"
description = "Add structured data (Schema.org JSON-LD) to your website to improve SEO."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/YourOnly-One/hugo-semantic-web"

# If you have a running demo of the theme.
#demosite = "https://gohugo.io"

tags = ["SEO", "JSON-LD", "Schema.org", "Structured Data", "Linked Data", "SemWeb", "YourOnly.One"]
features = ["Organization", "WebSite", "WebPage", "WebContent", "Article", "BlogPosting", "Person", "ImageObject", "VideObject"]

# If the theme has multiple authors
#authors = [
#  {name = "Name of author", homepage = "Website of author"},
#  {name = "Name of author", homepage = "Website of author"}
#]

# If the theme has a single author
[author]
  name = "YourOnly.One"
  homepage = "https://youronly.one"

# If porting an existing theme
[original]
  author = "Martijn00"
  homepage = "https://baseflow.com"
  repo = "https://github.com/Baseflow/HugoStructuredData"
